* exercism-mode
  :PROPERTIES:
  :CUSTOM_ID: exercism-el
  :END:
Exercism mode for Emacs, using the exercism CLI tool.

** Description
This is a minor mode for working with [[https://exercism.io][Exercism]] problems within Emacs. It integrates with [[https://github.com/bbatsov/projectile][projectile-mode]] to use your problem's directory as it's own directory project root. Each programming problem is its own projectile project, which will give you all the features projectile offers for defined projects. The function for finding the project root is ~push~-ed to projectile's ~projectile-project-root-functions~ list, so it will check if your project is in your Exercism workspace, and act accordingly, before any other functions for finding your project root is run. The projectile-project-root function for this mode first looks for ~.exercism/metadata.json~ and upon failing that, looks for where the directory structure rests within the configured exercism workspace. This is especially beneficial, if your Exercism workspace directory is being stored in a VCS, like git.
** Installation
*** Clone the repo
#+begin_src shell
git clone https://github.com/timotheosh/exercism-mode/
#+end_src

*** Vanilla Emacs
**** Install ~projectile~
Follow the quickstart guide for installing projectile [[https://github.com/bbatsov/projectile][here]].
**** Add ~exercism-mode~ to your emacs config.
Add to your ~~/.emacs.d/init.el~ the following:
#+begin_src emacs-lisp
(add-to-list 'load-path "<path to exercism-mode repo>")
(require 'projectile)
(require 'exercism-mode)
(add-hook 'projectile-mode-hook 'exercism-mode)
#+end_src
*** Using ~use-package~
**** Install ~projectile~
Follow the quickstart guide for installing projectile [[https://github.com/bbatsov/projectile][here]].
**** Add ~exercism-mode~ to your emacs config.
Add to your ~~/.emacs.d/init.el~ the following:
#+begin_src emacs-lisp
(use-package exercism-mode
  :load-path "<path to exercism-mode repo>"
  :config
  (add-hook 'projectile-mode-hook 'exercism-mode))
#+end_src
*** Doom Emacs
**** Installation for Doom Emacs
Add the following to your ~packages.el~:
#+begin_src emacs-lisp
(package! exercism-mode :recipe (:host github :repo "timotheosh/exercism-mode"))
#+end_src
**** Config for Doom Emacs
There is nothing else needed to use ~exercism-mode~ in Doom Emacs.
** Features
1. Minor mode adds a function to find your exercism problem project directory.
2. ~M-x exercism~ Opens a dired session in your Exercism workspace root.
